CI

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -13,14 +13,14 @@ concurrency:
 env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}
-  JULIA_NUM_THREADS: 2
   PYTHON_VER: '3.10'
 
 jobs:
   docker:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
       - uses: docker/setup-buildx-action@v2
       - name: Build and cache Docker Image
         uses: docker/build-push-action@v3
@@ -34,11 +34,15 @@ jobs:
 
   execute:
     needs: docker
+    env:
+      JULIA_NUM_THREADS: 2
+      JUPYTER_TIMEOUT: 600
     strategy:
       fail-fast: false
       matrix:
+        # Notebooks need to be executed
         notebook:
-          - 01-fromode
+          - 01-manual
           - 02-heat
           - 03-brusselator
     runs-on: ubuntu-latest
@@ -55,10 +59,11 @@ jobs:
           cache-from: type=gha
       - name: Execute Notebook
         run: >
-          docker run -v ${{ github.workspace }}:/work
+          docker run
+          -v ${{ github.workspace }}:/work
           -e JULIA_NUM_THREADS=${{ env.JULIA_NUM_THREADS }}
           ${{ env.IMAGE_NAME }}:test
-          jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --inplace
+          jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=${{ env.JUPYTER_TIMEOUT }} --execute --inplace
           /work/docs/${{ matrix.notebook }}.ipynb
       - name: Upload Notebook
         uses: actions/upload-artifact@v3
@@ -69,6 +74,9 @@ jobs:
   jupyter-book:
     needs: execute
     runs-on: ubuntu-latest
+    # store success output flag for ci job
+    outputs:
+      success: ${{ steps.setoutput.outputs.success }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -76,9 +84,10 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: ${{ env.PYTHON_VER }}
+          cache: 'pip'
+          cache-dependency-path: '.ci/requirements.txt'
       - name: Install dependencies
-        run: pip install jupyter-book
-      - run: mkdir -p out
+        run: pip install -r .ci/requirements.txt
       - name: Download notebooks
         uses: actions/download-artifact@v3
         with:
@@ -87,20 +96,46 @@ jobs:
         run: find out/ -type f -iname '*.ipynb' -exec mv -t docs/ {} +
       - name: Build website
         run: jupyter-book build docs/ -W -v
+      - name: Set output flag
+        id: setoutput
+        run: echo "::set-output name=success::true"
       - name: Setup Pages
+        if: github.ref == 'refs/heads/main'
         id: pages
         uses: actions/configure-pages@v2
       - name: Upload page artifact
+        if: github.ref == 'refs/heads/main'
         uses: actions/upload-pages-artifact@v1
         with:
           path: docs/_build/html
 
+  # This job is for GitHub status check
+  # https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
+  ci:
+    needs: [execute, jupyter-book]
+    runs-on: ubuntu-latest
+    if: always() # always run, so we never skip the check
+    steps:
+      # pass step only when output of previous jupyter-book job is set
+      # in case at least one of the execution fails, jupyter-book is skipped
+      # and the output will not be set, which will then cause the ci job to fail
+      - run: |
+          passed="${{ needs.jupyter-book.outputs.success }}"
+          if [[ $passed == "true" ]]; then
+            echo "Tests passed"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
+          fi
+
   docker-push:
-    needs: [execute, docker]
+    needs: [docker, execute]
     if: github.ref == 'refs/heads/main'
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
       - uses: docker/setup-buildx-action@v2
       - uses: docker/login-action@v2
         with:
